spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:argo
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
logging:
  level:
    org.hibernate.SQL: debug
